<html>
<head><title>Tasky</title></head>
<body>
Sign in:<br/>

<form action="<?php echo $this->url(array('controller' => 'index', 'action' => 'login'));?>">
    <table>
        <tr>
            <td><label for="email">Mail</label></td>
            <td><input type="text" name="email" id="email"></td>
        </tr>
        <tr>
            <td><label for="pass">Password</label></td>
            <td><input type="password" name="pass" id="pass"></td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit"></td>
        </tr>
    </table>
</form>
<form action="<?php echo $this->url(array('controller' => 'index', 'action' => 'openidlogin'));?>">
    <label for="openid">OpenID</label>: <input type="text" name="openid" id="openid">
</form>

<a href="<?php echo $this->url(array('controller' => 'play', 'action' => 'index', 'newuser' => '1'));?>">Try it</a>
</body>
</html>