<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('task', 'task_owner_id_user_id', array(
             'name' => 'task_owner_id_user_id',
             'local' => 'owner_id',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('task', 'task_parent_id_task_id', array(
             'name' => 'task_parent_id_task_id',
             'local' => 'parent_id',
             'foreign' => 'id',
             'foreignTable' => 'task',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('task', 'task_owner_id_user_id');
        $this->dropForeignKey('task', 'task_parent_id_task_id');
    }
}