<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtask extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('task', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'label' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'complete' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'creation' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'modification' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'x' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'y' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'page' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'dropped' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'parent_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'owner_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_unicode_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('task');
    }
}