<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('user', 'user_roottask_id_task_id', array(
             'name' => 'user_roottask_id_task_id',
             'local' => 'roottask_id',
             'foreign' => 'id',
             'foreignTable' => 'task',
             ));
        $this->addIndex('user', 'user_roottask_id', array(
             'fields' => 
             array(
              0 => 'roottask_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('user', 'user_roottask_id_task_id');
        $this->removeIndex('user', 'user_roottask_id', array(
             'fields' => 
             array(
              0 => 'roottask_id',
             ),
             ));
    }
}