<?php

/**
 * Task
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Task extends BaseTask
{
    public function toJsonObj(){
        $out = new stdclass();
        $out->id = $this->id;
        $out->label = $this->label;
        $out->x = $this->x;
        $out->y = $this->y;
        $out->marked = $this->complete;
        $out->subs = array();

        if(!$this->page){
            $children = $this->Subtasks;
            foreach($children as $child){
                $out->subs[]=$child->toJsonObj();
            }
        }
        return $out;
    }
}