<a href="<?php echo $this->url(array('controller'=>'doctrine','action'=>'migr-init')); ?>">Generate Migrations from Models</a><br />
<a href="<?php echo $this->url(array('controller'=>'doctrine','action'=>'gen-models')); ?>">Generate Models from YAML</a><br />
<a href="<?php echo $this->url(array('controller'=>'doctrine','action'=>'show')); ?>">Show current DB scheme version</a><br />
<a href="<?php echo $this->url(array('controller'=>'doctrine','action'=>'migrate')); ?>">Apply Migrations</a><br />
<a href="<?php echo $this->url(array('controller'=>'doctrine','action'=>'diff')); ?>">Generate Migrations from YAML diff</a><br />